Az Azure Functions [eseményindítók és kötések](..\articles\azure-functions\functions-triggers-bindings.md) különböző Azure-szolgáltatásokkal kommunikálni. Ha ezekkel a szolgáltatásokkal integrálja, előfordulhat, hogy jelenik meg a hibákat, az API-kat az alapul szolgáló Azure-szolgáltatáshoz származik. Hibák akkor is előfordulhat, ha REST vagy ügyfél tárak segítségével más szolgáltatásokkal, a függvény kódból kommunikálni próbál. Az adatok elvesztésének elkerüléséhez fel, és a funkciók helyes működését, fontos vagy forrásból hibák kezelésének.

A legtöbb eseményindítók van nincs beépített újrapróbálkozás függvény végrehajtása során hibák esetén. A két eseményindítók újrapróbálkozási támogatás a következők: Azure Queue storage és az Azure Blob Storage tárolóban. Alapértelmezés szerint ezek az eseményindítók ismétlődnek, legfeljebb öt alkalommal. Az ötödik ismételt próbálkozás után is eseményindítók üzenetet írni egy speciális [poison várólista](..\articles\azure-functions\functions-bindings-storage-queue.md#trigger---poison-messages). 

Kell hiba fordulhat elő, a függvény az eseményindítóra vonatkozó információt az adatvesztés elkerülése érdekében, ajánlott, hogy try-catch blokkok a függvény kódban van szüksége az esetleges hibákat. Hiba esetén az adatok lettek átadva a függvénynek az eseményindító által különleges "poison" várólistához írni. Ez a módszer megegyezik egy használják a [Blob storage eseményindító](..\articles\azure-functions\functions-bindings-storage-blob.md#trigger---poison-blobs). 

Ezzel a módszerrel rögzítheti eseményindító eseményeket, amelyek is hibák miatt megszakadt és funkcióval egy másik folyamat üzenetek tárolt információk segítségével ártalmas várólistából egy későbbi időpontban újra őket.  